### ISSUE TITLE
Properly escape JavaScript comments

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-fiddle#11]
Seems if the JS comments include HTML elements, then mounting code creates extra elements

Works
```js
'single a': {
      only: false,
      html: source`
        <a id="single">Single anchor</a>
      `,
      test: source`
        // yields "a"
        cy.get('a').should('have.id', 'single')
      `
    }
```
No surprises

<img width="1277" alt="Screen Shot 2019-09-09 at 3 44 46 PM" src="https://user-images.githubusercontent.com/2212006/64561538-fbe0cb80-d318-11e9-9a1b-f08f951869a0.png">

But if the test has comment like `// <a>`

```js
'single a': {
      only: false,
      html: source`
        <a id="single">Single anchor</a>
      `,
      test: source`
        // yields <a>
        cy.get('a').should('have.id', 'single')
      `
    }
```
Then the live markup contains additional empty anchor tag

<img width="1282" alt="Screen Shot 2019-09-09 at 3 45 08 PM" src="https://user-images.githubusercontent.com/2212006/64561576-19159a00-d319-11e9-8c78-17a4373f92ec.png">

**Comment by brettz9** [comment]
Btw, could the code be adjusted to allow `test` to just be a function to get syntax highlighting out of the box?

(I suppose that if you have to stringify it for some reason, that this could be a little confusing to some users (since the function would lose context))

**Comment by gpetrioli** [comment]
The problem seems to be with using `source`. 
That comes from https://github.com/declandewet/common-tags and is an alias for `html`.

Try without using `source` for the `test`.
