### ISSUE TITLE
Add Markdown preprocessor

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-fiddle#14]
After looking at Cypress documentation and how to use this fiddle to insert checked tests into the Hexo Markdown in https://github.com/cypress-io/cypress-documentation/pull/2063 I think I should do the following:

- allow Cypress to run tests from Markdown files if it finds appropriately tagged html / javascript code blocks

Maybe something like this
```
<!-- cypress-fiddle --->
## Fiddle title
This is test description

    html to mount


    cy.get(...)
    // and the rest of the test
<!-- cypress-fiddle-end --->
```

**Comment by brettz9** [comment]
It'd be nice I think if the JavaScript could be within a fenced ```` ```js ```` block so that when editing the file in a Markdown editor, one could get syntax highlighting without need for a separate cypress-aware IDE. Likewise for the HTML blocks. Comments (such as in your example) could immediately precede these blocks, however (as is done in [eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown#configuration-comments), for example).

**Comment by bahmutov** [comment]
yes, I agree @brettz9 that JS to run and HTML to mount should be fenced code blocks, but it was hard to code it inside a code block in GitHub text area :)
