### ISSUE TITLE
ReferenceError: `Cypress` is not defined

### ISSUE THREAD

**Issue by JoeSchr** [cypress-io/cypress-fiddle#77]
Trying to start this via codesandbox (to fiddle around) I get this error right out the gate:
```
ReferenceError
Cypress is not defined
evaluate
/src/index.js:7
   4 | const { createMarkdown } = require('safe-marked')
   5 | const markdown = createMarkdown()
   6 | 
>  7 | Cypress.Commands.add('runExample', options => {
   8 |   const { name, description, html, test } = options
   9 |   const testTitle = name || cy.state('runnable').title
  10 | 
View compiled
```

Link for reproduction: https://codesandbox.io/s/github/cypress-io/cypress-fiddle

**Comment by bahmutov** [comment]
The code examples are meant to run only inside Cypress test runner https://github.com/cypress-io/cypress and cannot be executed from a website.

**Comment by JoeSchr** [comment]
Ah, gotcha, thx!

**Comment by JoeSchr** [comment]
are you open for a PR that has a docker-compose service with cypress already installed?

**Comment by bahmutov** [comment]
Sure - but what’s the situation there? How would it work?

**Comment by JoeSchr** [comment]
I imagined it that then it would just work on online editor services like:
codepen.io, codesandbox.io and coder.io and I would just have copy & pasted
my already written docker-compose configuration. But I just realized you
have to expose `$DISPLAY` for `cypress open` and then your actual machine
had to have a port open from public to route $DISPLAY to your xhost. That
seems like a lot more hassle then I imagined when I wrote that.

Sorry about that!

But let me say, I really love love what I have seen so far from cypress.io.
Thank you for building it! I'm really looking forward converting all my e2e
and frontend unit tests to it!

**Comment by Iiqra** [comment]
Hi @JoeSchr,

Any lead on this issue, did you find a workaround? I'm new to Cypress. I faced the same issue when I imported a react project with testing implemented in Cypress to CodeSandbox, it was working all fine locally; however,  on import to CodeSendbox, I was unable to run my tests.

I have read the complete thread and understood the reason behind this behavior, but still, I want to know if you found out any working hack to this issue.

**Comment by JoeSchr** [comment]
@Iiqra sadly no

My "workaround" was to get a free trial at one of the Dev cloud providers like linode or Digitalocean . There you have more control over your environment and can either install a minimal X11 Server or pass $Display along to your local machine via ssh
